
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring;
import org.datacontract.schemas._2004._07.urenregistratieservice.TaakSet;
import org.datacontract.schemas._2004._07.urenregistratieservice.UserSet;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IUrenregistratieservice", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    org.datacontract.schemas._2004._07.urenregistratieservice.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IUrenregistratieservice {


    /**
     * 
     * @param gebruikersnaam
     * @param wachtwoord
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "Login", action = "http://tempuri.org/IUrenregistratieservice/Login")
    @WebResult(name = "LoginResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Login", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginResponse")
    public Boolean login(
        @WebParam(name = "gebruikersnaam", targetNamespace = "http://tempuri.org/")
        String gebruikersnaam,
        @WebParam(name = "wachtwoord", targetNamespace = "http://tempuri.org/")
        String wachtwoord);

    /**
     * 
     * @param gebruikersnaam
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "Registreer", action = "http://tempuri.org/IUrenregistratieservice/Registreer")
    @WebResult(name = "RegistreerResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Registreer", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Registreer")
    @ResponseWrapper(localName = "RegistreerResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RegistreerResponse")
    public Boolean registreer(
        @WebParam(name = "gebruikersnaam", targetNamespace = "http://tempuri.org/")
        String gebruikersnaam);

    /**
     * 
     * @param gebruikersnaam
     * @param wachtwoord
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "TakenOphalen", action = "http://tempuri.org/IUrenregistratieservice/TakenOphalen")
    @WebResult(name = "TakenOphalenResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TakenOphalen", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TakenOphalen")
    @ResponseWrapper(localName = "TakenOphalenResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TakenOphalenResponse")
    public ArrayOfstring takenOphalen(
        @WebParam(name = "gebruikersnaam", targetNamespace = "http://tempuri.org/")
        String gebruikersnaam,
        @WebParam(name = "wachtwoord", targetNamespace = "http://tempuri.org/")
        String wachtwoord);

    /**
     * 
     * @param gebruikersnaam
     * @param taak
     * @param wachtwoord
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "GewerkteUrenOphalen", action = "http://tempuri.org/IUrenregistratieservice/GewerkteUrenOphalen")
    @WebResult(name = "GewerkteUrenOphalenResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GewerkteUrenOphalen", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GewerkteUrenOphalen")
    @ResponseWrapper(localName = "GewerkteUrenOphalenResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GewerkteUrenOphalenResponse")
    public Integer gewerkteUrenOphalen(
        @WebParam(name = "taak", targetNamespace = "http://tempuri.org/")
        String taak,
        @WebParam(name = "gebruikersnaam", targetNamespace = "http://tempuri.org/")
        String gebruikersnaam,
        @WebParam(name = "wachtwoord", targetNamespace = "http://tempuri.org/")
        String wachtwoord);

    /**
     * 
     * @param gebruikersnaam
     * @return
     *     returns org.datacontract.schemas._2004._07.urenregistratieservice.UserSet
     */
    @WebMethod(operationName = "GebruikerOphalen", action = "http://tempuri.org/IUrenregistratieservice/GebruikerOphalen")
    @WebResult(name = "GebruikerOphalenResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GebruikerOphalen", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GebruikerOphalen")
    @ResponseWrapper(localName = "GebruikerOphalenResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GebruikerOphalenResponse")
    public UserSet gebruikerOphalen(
        @WebParam(name = "gebruikersnaam", targetNamespace = "http://tempuri.org/")
        String gebruikersnaam);

    /**
     * 
     * @param uren
     * @param gebruikersnaam
     * @param taak
     * @param wachtwoord
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "UrenOpslaan", action = "http://tempuri.org/IUrenregistratieservice/UrenOpslaan")
    @WebResult(name = "UrenOpslaanResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UrenOpslaan", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UrenOpslaan")
    @ResponseWrapper(localName = "UrenOpslaanResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UrenOpslaanResponse")
    public Boolean urenOpslaan(
        @WebParam(name = "taak", targetNamespace = "http://tempuri.org/")
        String taak,
        @WebParam(name = "uren", targetNamespace = "http://tempuri.org/")
        Integer uren,
        @WebParam(name = "gebruikersnaam", targetNamespace = "http://tempuri.org/")
        String gebruikersnaam,
        @WebParam(name = "wachtwoord", targetNamespace = "http://tempuri.org/")
        String wachtwoord);

    /**
     * 
     * @param gebruikersnaam
     * @param taak
     * @param wachtwoord
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "TaakVerwijderen", action = "http://tempuri.org/IUrenregistratieservice/TaakVerwijderen")
    @WebResult(name = "TaakVerwijderenResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TaakVerwijderen", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TaakVerwijderen")
    @ResponseWrapper(localName = "TaakVerwijderenResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TaakVerwijderenResponse")
    public Boolean taakVerwijderen(
        @WebParam(name = "taak", targetNamespace = "http://tempuri.org/")
        String taak,
        @WebParam(name = "gebruikersnaam", targetNamespace = "http://tempuri.org/")
        String gebruikersnaam,
        @WebParam(name = "wachtwoord", targetNamespace = "http://tempuri.org/")
        String wachtwoord);

    /**
     * 
     * @param gebruikersnaam
     * @param taak
     * @return
     *     returns org.datacontract.schemas._2004._07.urenregistratieservice.TaakSet
     */
    @WebMethod(operationName = "TaakOphalen", action = "http://tempuri.org/IUrenregistratieservice/TaakOphalen")
    @WebResult(name = "TaakOphalenResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TaakOphalen", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TaakOphalen")
    @ResponseWrapper(localName = "TaakOphalenResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TaakOphalenResponse")
    public TaakSet taakOphalen(
        @WebParam(name = "taak", targetNamespace = "http://tempuri.org/")
        String taak,
        @WebParam(name = "gebruikersnaam", targetNamespace = "http://tempuri.org/")
        String gebruikersnaam);

}
